version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14.11.0 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "npm installing" # run the `echo` command
      - run: npm install # run the `npm install` command
      - run: npm cache clean --force
      - run: npm run build # run the `npm run build` command
  test:
    docker:
      - image: circleci/node:14.11.0 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "testing" # run the `echo` command
      - run: npm install # run the `npm install` command
      - run: npm test # run the `npm test` command
  hithere:
    docker:
      - image: circleci/node:14.11.0 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hellooooo!" # run the `echo` command
workflows:
  version: 2.1
  build_test_and_lint:
    jobs:
      - build
      - hithere
      - test:
          requires:
            - hithere # the test script required the hithere script to pass before it can be run
